### ISSUE TITLE
support "donate some ${number} of contributions in units of ${number}"

### ISSUE THREAD

**Issue by slippycheeze** [dpk5081/eso-guild-contributions#14]
Our guild operates on what I suspect is a relatively common model for contributions:

 * Donations are in units of 1,000 gold, to the guild bank.
 * Any number of donations, including zero, are acceptable.
 * Donations on Saturday or Sunday preferred, but not mandatory.
 * Each unit of donation gives one "ticket" in a random draw for prizes.

To work well with that, it'd be good to specify the donation unit, then have the ability to donate 1 or more units in the "Guild Contributions" window.   A counter tracking the number of units contributed, and the amount of gold, would be great.

I imagine the "how much to contribute" being a number field with plus/minus buttons next to it, above the "and now do it" button.

If you have further questions, I'm @SlippyCheeze in-game, PC-NA, but I'll try to keep an eye out here too.

**Comment by dpkristensen** [comment]
Interesting idea; it is very similar to my guild as well, except contributions were recently changed to mandatory.  The contributions tracking is primarily for "mandatory minimum" requirements so you don't forget; it doesn't stop you from giving more manually.

If you just want a record of whether you considered contributing, I would suggest the manual method.

Maybe there could be a general purpose multiplier in the contributions window, though.
