### ISSUE TITLE
chat message indicating the amount of money deposited

### ISSUE THREAD

**Issue by slippycheeze** [dpk5081/eso-guild-contributions#15]
It'd be nice to have a chat message confirming that a contribution had been submitted to the bank.

Possibly also a display on the contribution window showing how much the previous week contribution was.

**Comment by dpkristensen** [comment]
Right now the contribution amount is fixed in terms of gold.  In the future, contribution tracking could be more complex and not necessarily gold-based; I think it should be possible, though.
