### ISSUE TITLE
guild list order

### ISSUE THREAD

**Issue by Moritz2112** [dpk5081/eso-guild-contributions#9]
It appears to only update the first guild in my list, from what I can tell so far.  ROD is fourth...  Been pondering dropping those three guilds anyway as they are pretty much completely inactive now...

**Comment by dpkristensen** [comment]
I'm in 3/5 guilds, and I see all 3 listed.  The settings menu will show all 5 guild slots regardless of whether you're in them.  Questions:

* What does it show in the settings menu for the other slots?
* If the guilds are listed, what do you have the rule and method set to for the other guilds?

A screenshot would be nice, but just a text description of the settings shown works too.

**Comment by dpkristensen** [comment]
Fixed several issues in 0.02.  I haven't had any issues.  Please re-open if you can reproduce and provide any more information.
